export default {
  dashboard: 'Dashboard at a glance',
  platforms: 'Connecting review platforms',
  'brand-voice': 'Brand voice',
  'reviews-tab': 'The Reviews tab',
  'routing-rules': 'Routing rules',
  campaigns: 'Campaigns',
  templates: 'Message templates & A/B testing',
  notifications: 'Notifications',
  'multi-location': 'Multi-location',
  recovery: 'Service recovery',
  'trust-score': 'Trust Score',
  'trust-assets': 'Trust assets',
  competitors: 'Competitors',
  'ai-visibility': 'AI visibility',
  reports: 'Monthly ROI reports',
}
